# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_cos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
